#:schema node_modules/wrangler/config-schema.json
name = "the-master-collective"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "master-collective-db"
database_id = "local"
